### PR TITLE
New prop to let user switch size to large.

### PR DESCRIPTION
**Pull request by kamilwylegala**
Hello!

I found your component very useful! I'd like to extend it a bit.

Bootstrap modal component supports `modal-lg` class which changes size of modal. I added in your component new prop that lets users to change size. By default = false.

What do you think?

Thanks in advance for review.

### CODE REVIEW

**Comment by joturako** [comment]
@kamilwylegala hi, thanks for contributing! I think we can do in better to support other sizes like `modal-sm` as well. I am thinking about a `size` property that can be either `normal` (default) `large` or `small`. What do you think?  I appreciate if you can do it that way to cover more use cases :)

**Comment by kamilwylegala** [comment]
Sure, I can handle it :)

Now actually I'm thinking about something like:
```html
<div :class="['modal-dialog', size]" role="document">
```
to let define any class. We could provide then e.g. `modal-lg` string or leave it empty. It'd be also open for differens sizes.

Or do you prefer some predefined values this component should support?

**Comment by joturako** [comment]
@kamilwylegala Actually that sound good, but we should rename it to `:extraClasses` (an array of classes to apply to the component). That allows you to defines extra class styles and then apply it to the component whenever you like.

**Comment by joturako** [comment]
@kamilwylegala actually we can always use `v-bind:class` directive to add any custom classes to the top element, so let's go back to `size` with values like `large` or `small` to add `modal-lg` or `modal-sm` to the `modal-dialog` element.

**Comment by joturako** [comment]
@kamilwylegala please see this branch I modified https://github.com/joturako/vue2-bootstrap-modal/tree/size_classes If you're ok with that, please modify your version and I am happy to merge your PR 👍

**Comment by joturako** [comment]
@kamilwylegala Nice PR! I'm gonna update the version to `0.1.7`, with some changes to README, then push it to `npm`. Thanks again for the contribution 💯 !

**Pull request merged**
